### ISSUE TITLE
npm start doesn't work

### ISSUE THREAD

**Issue by abr4xas** [mafintosh/webplay#1]
``` bash
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.1.11
3 info using node@v0.10.33
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart webplay@1.0.0
7 info start webplay@1.0.0
8 verbose unsafe-perm in lifecycle true
9 info webplay@1.0.0 Failed to exec start script
10 verbose stack Error: webplay@1.0.0 start: `wzrd index.js:bundle.js`
10 verbose stack Exit status 127
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:212:16)
10 verbose stack     at EventEmitter.emit (events.js:98:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:98:17)
10 verbose stack     at maybeClose (child_process.js:756:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
11 verbose pkgid webplay@1.0.0
12 verbose cwd /Users/abr4xas/Documents/git/webplay
13 error Darwin 11.4.2
14 error argv "node" "/usr/local/bin/npm" "start"
15 error node v0.10.33
16 error npm  v2.1.11
17 error code ELIFECYCLE
18 error webplay@1.0.0 start: `wzrd index.js:bundle.js`
18 error Exit status 127
19 error Failed at the webplay@1.0.0 start script 'wzrd index.js:bundle.js'.
19 error This is most likely a problem with the webplay package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     wzrd index.js:bundle.js
19 error You can get their info via:
19 error     npm owner ls webplay
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
```

**Comment by abr4xas** [comment]
Sorry, i forgot run `npm install` :P
